# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='poetry.proto',
  package='poetry',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpoetry.proto\x12\x06poetry\"\x14\n\x04Seed\x12\x0c\n\x04Text\x18\x01 \x01(\t\"\x16\n\x06Poetry\x12\x0c\n\x04Text\x18\x01 \x01(\t2@\n\x0eGeneratePoetry\x12.\n\x0eGeneratePoetry\x12\x0c.poetry.Seed\x1a\x0e.poetry.Poetryb\x06proto3')
)




_SEED = _descriptor.Descriptor(
  name='Seed',
  full_name='poetry.Seed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='poetry.Seed.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_POETRY = _descriptor.Descriptor(
  name='Poetry',
  full_name='poetry.Poetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='poetry.Poetry.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Seed'] = _SEED
DESCRIPTOR.message_types_by_name['Poetry'] = _POETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Seed = _reflection.GeneratedProtocolMessageType('Seed', (_message.Message,), dict(
  DESCRIPTOR = _SEED,
  __module__ = 'poetry_pb2'
  # @@protoc_insertion_point(class_scope:poetry.Seed)
  ))
_sym_db.RegisterMessage(Seed)

Poetry = _reflection.GeneratedProtocolMessageType('Poetry', (_message.Message,), dict(
  DESCRIPTOR = _POETRY,
  __module__ = 'poetry_pb2'
  # @@protoc_insertion_point(class_scope:poetry.Poetry)
  ))
_sym_db.RegisterMessage(Poetry)



_GENERATEPOETRY = _descriptor.ServiceDescriptor(
  name='GeneratePoetry',
  full_name='poetry.GeneratePoetry',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=70,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='GeneratePoetry',
    full_name='poetry.GeneratePoetry.GeneratePoetry',
    index=0,
    containing_service=None,
    input_type=_SEED,
    output_type=_POETRY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERATEPOETRY)

DESCRIPTOR.services_by_name['GeneratePoetry'] = _GENERATEPOETRY

# @@protoc_insertion_point(module_scope)
